### ISSUE TITLE
why do vaas have differnet format between xc-mainnet and hermes?

### ISSUE THREAD

**Issue by jpeer** [pyth-network/pyth-crosschain#1106]
these two calls deliver different length of response:

curl https://xc-mainnet.pyth.network/api/latest_vaas\?ids\[\]\=0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43

curl https://hermes.pyth.network/api/latest_vaas\?ids\[\]\=0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43

anyone who could explain this, or is it documented somewhere? thanks!

**Comment by guibescos** [comment]
Hi, thanks for reaching out!

That's because xc-mainnet and hermes serve data in a different format.

Both xc-mainnet and hermes use Wormhole to verify prices from Pythnet.
The main difference is that :
- For xc-mainnet, each Wormhole message contains 5 price feeds (the groupings of 5 are fixed). This is inefficient because you need to verify Wormhole signatures multiple times if the price feeds you want to use are in different messages.
- For hermes, each Wormhole message contains all price feeds (with some Merkle tree magic), so that the receiver contract only needs to verify Wormhole signatures once for any number of price feeds that you might want to use.

hermes in the new and more efficient version. 
This blog contains some more background info :
https://pyth.network/blog/perseus-network-upgrade

**Comment by jpeer** [comment]
thanks for the explanation!
